import { photos } from "@/lib/images";
import type { SeedProperty } from "./seed-data";

/**
 * Additional realistic marketplace inventory in the style of popular Pakistani
 * portals (Zameen-style plots, houses and rentals across DHA, Bahria, Lake
 * City and scheme areas). All copy is original editorial content.
 */
export const extraPropertySeed: SeedProperty[] = [
  {
    slug: "5-marla-house-dha-phase-9-town-lahore",
    title: "5 Marla Brand New Designer House",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 9 Town",
    address: "Block D, DHA Phase 9 Town, Lahore",
    lat: 31.4215,
    lng: 74.4702,
    price: 16_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1125,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Brand new 5 Marla designer house in DHA Phase 9 Town with solid grey structure, Spanish tile roofing elevation and a proper mumty. Ground floor has drawing, dining and kitchen while the first floor carries two bedrooms with attached baths and a terrace.",
    features: [
      "Solid Awwal-grade construction",
      "Spanish elevation with tile work",
      "Powder room on ground floor",
      "Imported sanitary fittings",
      "Wiring for split ACs in all rooms",
    ],
    amenities: ["Gated society", "24/7 security", "Carpeted roads", "Nearby commercial", "Mosque nearby"],
    images: [photos.villas[5], photos.interiors[5], photos.bedrooms[6], photos.bedrooms[7], photos.interiors[1]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1920,
    daysAgo: 2,
  },
  {
    slug: "10-marla-house-bahria-orchard-phase-4-lahore",
    title: "10 Marla Corner House Near Gate",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Bahria Orchard Phase 4",
    address: "Block G-5, Bahria Orchard Phase 4, Lahore",
    lat: 31.3618,
    lng: 74.1994,
    price: 23_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 5,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Well-built 10 Marla corner house close to the Phase 4 gate in Bahria Orchard. Extra land on the side gives a bigger lawn, and the street is fully populated with families. Ideal for buyers who want Bahria facilities at an Orchard budget.",
    features: [
      "Corner plot with extra lawn",
      "Walking distance to gate and commercial",
      "Three-storey with mumty",
      "Separate servant quarter",
      "Bore plus Bahria water connection",
    ],
    amenities: ["Gated community", "Theme park nearby", "School and hospital", "Backup power", "Security patrol"],
    images: [photos.villas[4], photos.interiors[4], photos.bedrooms[5], photos.bedrooms[6], photos.interiors[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1340,
    daysAgo: 4,
  },
  {
    slug: "1-kanal-plot-file-dha-phase-10-lahore",
    title: "1 Kanal Affidavit File in DHA Phase 10",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 10",
    address: "DHA Phase 10, Lahore",
    lat: 31.4021,
    lng: 74.5233,
    price: 10_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 0,
    furnishing: "Not applicable",
    possession: "File",
    description:
      "1 Kanal affidavit file in DHA Phase 10 with complete documents and paid instalments. Verification available from the DHA office before token. Suitable for medium-term investors waiting for ballot and development announcements.",
    features: [
      "Complete file with receipts",
      "Instalments paid up to date",
      "Verification before token",
      "Clear seller title",
    ],
    amenities: ["DHA transfer procedure", "Escrow-friendly deal", "Documentation support"],
    images: [photos.dev[3], photos.dev[5], photos.dev[6], photos.dev[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 2210,
    daysAgo: 5,
  },
  {
    slug: "5-marla-possession-plot-lake-city-m7-lahore",
    title: "5 Marla Possession Plot in Lake City M-7",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Lake City",
    address: "Sector M-7, Lake City, Lahore",
    lat: 31.3524,
    lng: 74.2611,
    price: 9_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1125,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "Possession-ready 5 Marla plot in Lake City Sector M-7 on a 30-foot road near the park. All dues cleared with possession letter in hand. Surrounding streets are populated, so construction can start immediately.",
    features: [
      "Possession with allotment letter",
      "30-foot front road",
      "Near park and mosque",
      "All dues cleared",
    ],
    amenities: ["Gated community", "Golf course nearby", "Schools and commercial", "24/7 security"],
    images: [photos.dev[5], photos.dev[1], photos.dev[0], photos.dev[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1680,
    daysAgo: 6,
  },
  {
    slug: "2-bed-apartment-bahria-enclave-islamabad",
    title: "2 Bed Apartment with Margalla View",
    purpose: "buy",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "Bahria Enclave",
    address: "Sector H, Bahria Enclave, Islamabad",
    lat: 33.6312,
    lng: 73.2218,
    price: 13_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 2,
    bathrooms: 2,
    areaValue: 1100,
    areaUnit: "sqft",
    areaSqft: 1100,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Sunny 2-bedroom apartment in Bahria Enclave with a Margalla-facing balcony. The building has two lifts, standby generators and dedicated visitor parking. Popular with young families and Bahria Head Office staff.",
    features: [
      "Margalla-facing balcony",
      "Two lifts in building",
      "Standby generator backup",
      "Dedicated parking bay",
    ],
    amenities: ["Gated sector", "Cineplex and zoo nearby", "Jamia mosque", "Maintenance staff"],
    images: [photos.interiors[3], photos.bedrooms[1], photos.interiors[6], photos.bedrooms[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1210,
    daysAgo: 7,
  },
  {
    slug: "10-marla-house-g13-islamabad",
    title: "10 Marla Solid House in G-13",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "G-13",
    address: "G-13/2, Islamabad",
    lat: 33.6618,
    lng: 72.9923,
    price: 46_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 6,
    bathrooms: 6,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Solid 10 Marla double-storey house in G-13/2 with six bedrooms and a proper basement. The sector is fully developed with markets, schools and direct Kashmir Highway access. Documents complete with CDA transfer record.",
    features: [
      "Usable basement",
      "Six bedrooms with attached baths",
      "Two kitchens",
      "CDA sector with clear record",
    ],
    amenities: ["Developed sector", "Markets and schools", "Highway access", "Water and gas"],
    images: [photos.villas[6], photos.interiors[1], photos.bedrooms[3], photos.bedrooms[2], photos.interiors[9]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 990,
    daysAgo: 9,
  },
  {
    slug: "3-bed-flat-gulistan-johar-karachi-rent",
    title: "3 Bed Flat for Rent in Gulistan-e-Johar",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Gulistan-e-Johar",
    address: "Block 12, Gulistan-e-Johar, Karachi",
    lat: 24.9204,
    lng: 67.1322,
    price: 55_000,
    priceUnit: "month",
    negotiable: false,
    bedrooms: 3,
    bathrooms: 2,
    areaValue: 1350,
    areaUnit: "sqft",
    areaSqft: 1350,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Ventilated 3-bedroom flat on the second floor in Gulistan-e-Johar Block 12. West-open with boundary-wall project, sweet water and standby generator for common areas. Close to universities, hospitals and main Rashid Minhas Road.",
    features: [
      "West-open ventilated flat",
      "Boundary-wall project",
      "Sweet water supply",
      "Generator for common areas",
    ],
    amenities: ["Lift", "Security guard", "Nearby universities", "Market at walking distance"],
    images: [photos.bedrooms[5], photos.interiors[1], photos.bedrooms[3], photos.interiors[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1730,
    daysAgo: 3,
  },
  {
    slug: "120-sqyd-house-scheme-33-karachi",
    title: "120 Sq Yd Single-Storey House in Scheme 33",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Scheme 33",
    address: "Sector 35-A, Scheme 33, Karachi",
    lat: 24.9518,
    lng: 67.1834,
    price: 19_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1080,
    areaUnit: "sqft",
    areaSqft: 1080,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Single-storey 120 sq yard house in Scheme 33 Sector 35-A with leased documents. Strong structure with an RCC roof that can take another floor. The lane is populated and minutes from the M-9 link and main Superhighway.",
    features: [
      "Leased with complete documents",
      "RCC roof, second floor possible",
      "Populated lane",
      "Near M-9 link road",
    ],
    amenities: ["Water and electricity", "Nearby schools", "Masjid in street", "Public transport"],
    images: [photos.villas[2], photos.interiors[0], photos.bedrooms[5], photos.bedrooms[3]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1440,
    daysAgo: 8,
  },
  {
    slug: "8-marla-commercial-plot-bahria-phase-8-rawalpindi",
    title: "8 Marla Commercial Plot on Main Boulevard",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "rawalpindi",
    cityName: "Rawalpindi",
    locationArea: "Bahria Town Phase 8",
    address: "Business District, Bahria Town Phase 8, Rawalpindi",
    lat: 33.5124,
    lng: 73.1042,
    price: 42_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 8,
    areaUnit: "marla",
    areaSqft: 1800,
    parking: 0,
    furnishing: "Not applicable",
    possession: "Available",
    description:
      "8 Marla commercial plot facing the Business District boulevard in Bahria Town Phase 8. High-visibility location suited for a bank branch, retail outlet or clinic. Possession plot with numbers allotted.",
    features: [
      "Boulevard-facing commercial",
      "Possession plot, numbers allotted",
      "High footfall district",
      "Wide frontage",
    ],
    amenities: ["Business district", "Ample parking", "Security", "Nearby residential sectors"],
    images: [photos.dev[1], photos.dev[0], photos.dev[5]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 720,
    daysAgo: 12,
  },
  {
    slug: "5-marla-house-wapda-city-faisalabad",
    title: "5 Marla House in Wapda City",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "faisalabad",
    cityName: "Faisalabad",
    locationArea: "Wapda City",
    address: "Block B, Wapda City, Faisalabad",
    lat: 31.4022,
    lng: 73.0218,
    price: 11_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 3,
    areaValue: 5,
    areaUnit: "marla",
    areaSqft: 1125,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Neat 5 Marla double-storey house in Wapda City Block B. Four bedrooms with tiled flooring, a proper kitchen with cabinets and a mumty store. The block is fully populated with underground electrification.",
    features: [
      "Four bedrooms, three baths",
      "Fitted kitchen cabinets",
      "Underground electrification",
      "Populated block",
    ],
    amenities: ["Gated society", "Parks", "Carpeted roads", "Nearby schools"],
    images: [photos.villas[9], photos.interiors[4], photos.bedrooms[0], photos.bedrooms[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 610,
    daysAgo: 14,
  },
  {
    slug: "10-marla-house-bosan-road-multan-rent",
    title: "10 Marla Upper Portion for Rent on Bosan Road",
    purpose: "rent",
    category: "apartment",
    propertyType: "Upper Portion",
    citySlug: "multan",
    cityName: "Multan",
    locationArea: "Bosan Road",
    address: "Officers Colony, Bosan Road, Multan",
    lat: 30.1931,
    lng: 71.4932,
    price: 70_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1600,
    areaUnit: "sqft",
    areaSqft: 1600,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Independent 10 Marla upper portion on Bosan Road with a separate gate and separate meters. Three bedrooms with attached baths, a large terrace and a separate laundry area. Preferred for bank officers and medical professionals.",
    features: [
      "Separate gate and entrance",
      "Separate electricity and gas meters",
      "Large terrace",
      "Separate laundry area",
    ],
    amenities: ["Secure street", "Near hospitals", "Backup power", "Nearby market"],
    images: [photos.interiors[6], photos.bedrooms[2], photos.bedrooms[6]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "sana-ali",
    views: 540,
    daysAgo: 10,
  },
  {
    slug: "1-kanal-farmhouse-bedian-road-lahore-rent",
    title: "1 Kanal Farmhouse for Rent on Bedian Road",
    purpose: "rent",
    category: "farmhouse",
    propertyType: "Farmhouse",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Bedian Road",
    address: "Bedian Road, near DHA Phase 6, Lahore",
    lat: 31.4733,
    lng: 74.4618,
    price: 350_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 6,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "Lush 1 Kanal farmhouse on Bedian Road available for long-term rent. Four bedrooms, a swimming pool, servant quarter and a mango orchard boundary. Suitable for executives, farm stays and corporate retreats.",
    features: [
      "Swimming pool with deck",
      "Mango orchard boundary",
      "Servant quarter",
      "Corporate retreat friendly",
    ],
    amenities: ["Farmhouse community", "Security patrol", "Green surroundings", "Wide access road"],
    images: [photos.villas[3], photos.villas[9], photos.interiors[8], photos.bedrooms[4], photos.villas[1]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 880,
    daysAgo: 11,
  },
  // Market-realistic listings in established societies. Sizes, prices and
  // layouts follow what Pakistani portals such as Zameen and DHA-area dealers
  // typically advertise for these blocks; the copy itself is original.
  {
    slug: "1-kanal-modern-house-dha-phase-6-lahore",
    title: "1 Kanal Modern House with Basement, Block C",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 6",
    address: "Block C, DHA Phase 6, Lahore",
    lat: 31.4755,
    lng: 74.452,
    price: 98_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 3,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A 1 Kanal contemporary house on a 50-foot road in Block C, a short drive from the Phase 6 main boulevard and Raya. The ground floor has a double-height lounge, formal drawing and dining, and a kitchen with a separate working kitchen; the first floor carries three bedrooms with dressing rooms. The full basement has a home cinema and a guest suite.",
    features: [
      "Full basement with home cinema",
      "Double-height lounge with glass wall",
      "Separate working kitchen",
      "Five bedrooms with walk-in dressings",
      "Solar system with net metering",
      "Servant quarter and store",
    ],
    amenities: ["Gated society", "24/7 security", "Near main boulevard", "Parks nearby", "Underground electricity"],
    images: [photos.villas[0], photos.interiors[0], photos.bedrooms[0], photos.interiors[1], photos.bedrooms[1]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 1460,
    daysAgo: 3,
  },
  {
    slug: "500-sq-yd-bungalow-dha-phase-8-karachi",
    title: "500 Sq. Yd. Bungalow near Khayaban-e-Ittehad",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA Phase 8",
    address: "Zone A, DHA Phase 8, Karachi",
    lat: 24.787,
    lng: 67.073,
    price: 160_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 6,
    bathrooms: 7,
    areaValue: 4500,
    areaUnit: "sqft",
    areaSqft: 4500,
    parking: 4,
    furnishing: "Semi-Furnished",
    possession: "Available",
    description:
      "A 500 square-yard west-open bungalow in DHA Phase 8, minutes from Khayaban-e-Ittehad and the sea-facing commercial belt. Six bedrooms across two floors, a family lounge on each level, a basement with a gym and a landscaped front lawn with covered parking for four cars.",
    features: [
      "West-open corner position",
      "Basement gym and store",
      "Family lounge on each floor",
      "Italian kitchen with island",
      "Covered parking for four cars",
    ],
    amenities: ["Gated society", "24/7 security", "Near beach", "Commercial nearby", "Wide roads"],
    images: [photos.villas[1], photos.interiors[2], photos.bedrooms[2], photos.interiors[3], photos.bedrooms[3]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 1310,
    daysAgo: 4,
  },
  {
    slug: "272-sq-yd-villa-precinct-10-bahria-town-karachi",
    title: "272 Sq. Yd. Luxury Villa in Precinct 10-A",
    purpose: "buy",
    category: "house",
    propertyType: "Villa",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "Bahria Town Karachi",
    address: "Precinct 10-A, Bahria Town Karachi",
    lat: 25.005,
    lng: 67.308,
    price: 34_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 2448,
    areaUnit: "sqft",
    areaSqft: 2448,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A ready-to-move 272 square-yard villa in Precinct 10-A, one of the most settled precincts close to the main Jinnah Avenue and the theme park. Four bedrooms with attached baths, a drawing room, TV lounge and a covered car porch. Utilities, gas and water are connected and the villa has been kept in original condition.",
    features: [
      "Ready to move",
      "Four bedrooms with attached baths",
      "TV lounge and drawing room",
      "Covered car porch",
      "Gas, water and electricity connected",
    ],
    amenities: ["Gated society", "24/7 security", "Near Jinnah Avenue", "Mosque nearby", "Parks nearby"],
    images: [photos.villas[2], photos.interiors[4], photos.bedrooms[4], photos.interiors[5]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "bilal-shaikh",
    views: 970,
    daysAgo: 6,
  },
  {
    slug: "1-kanal-house-sector-f-dha-phase-2-islamabad",
    title: "1 Kanal Designer House in Sector F",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 2",
    address: "Sector F, DHA Phase 2, Islamabad",
    lat: 33.529,
    lng: 73.156,
    price: 82_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A 1 Kanal designer house in Sector F, DHA Phase 2, close to the GT Road entrance and the Sector F commercial. The layout puts a guest bedroom and drawing-dining on the ground floor, three bedrooms and a family lounge upstairs, and a separate annexe on the roof. Finished with porcelain tiles, wooden flooring in the bedrooms and a stone-clad front elevation.",
    features: [
      "Stone-clad front elevation",
      "Wooden flooring in bedrooms",
      "Rooftop annexe with bath",
      "Guest bedroom on ground floor",
      "Solar-ready wiring",
    ],
    amenities: ["Gated society", "24/7 security", "Near GT Road entrance", "Commercial nearby", "Parks nearby"],
    images: [photos.villas[3], photos.interiors[6], photos.bedrooms[5], photos.interiors[7], photos.bedrooms[6]],
    featured: true,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 1120,
    daysAgo: 5,
  },
  {
    slug: "2-bed-apartment-emaar-canyon-views-islamabad-rent",
    title: "2 Bed Furnished Apartment in Emaar Canyon Views",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "Emaar Canyon Views",
    address: "Canyon Views, DHA Phase 2, Islamabad",
    lat: 33.5415,
    lng: 73.11,
    price: 220_000,
    priceUnit: "month",
    negotiable: false,
    bedrooms: 2,
    bathrooms: 2,
    areaValue: 1450,
    areaUnit: "sqft",
    areaSqft: 1450,
    parking: 1,
    furnishing: "Furnished",
    possession: "Available",
    description:
      "A furnished two-bedroom apartment in Emaar Canyon Views with hill views from the lounge and master bedroom. The community has a clubhouse, gym, swimming pool and round-the-clock security, and the apartment comes with a fitted kitchen, split ACs and one reserved parking bay. Suitable for a family or corporate lease.",
    features: [
      "Fully furnished with split ACs",
      "Hill views from lounge and master bedroom",
      "Fitted kitchen with appliances",
      "Reserved parking bay",
      "Corporate lease welcome",
    ],
    amenities: ["Clubhouse", "Gym", "Swimming pool", "24/7 security", "Backup power"],
    images: [photos.interiors[8], photos.bedrooms[7], photos.interiors[9], photos.bedrooms[0]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 760,
    daysAgo: 2,
  },
  {
    slug: "1-kanal-house-for-rent-model-town-lahore",
    title: "1 Kanal Renovated House for Rent, Block G",
    purpose: "rent",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "Model Town",
    address: "Block G, Model Town, Lahore",
    lat: 31.483,
    lng: 74.326,
    price: 350_000,
    priceUnit: "month",
    negotiable: true,
    bedrooms: 5,
    bathrooms: 5,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 4500,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A renovated 1 Kanal double-storey house in Block G, Model Town, on a tree-lined road close to Model Town Link Road and the park. Five bedrooms, two lounges, a new kitchen and freshly redone bathrooms, with a large front lawn and a separate servant quarter. Available for a family on a one-year lease.",
    features: [
      "Freshly renovated kitchen and baths",
      "Large front lawn",
      "Two lounges",
      "Separate servant quarter",
      "Close to Model Town park",
    ],
    amenities: ["Society security", "Parks nearby", "Schools nearby", "Mosque nearby", "Markets nearby"],
    images: [photos.villas[4], photos.interiors[0], photos.bedrooms[1], photos.interiors[2]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "hassan-rizvi",
    views: 640,
    daysAgo: 1,
  },
  {
    slug: "10-marla-plot-overseas-block-park-view-city-islamabad",
    title: "10 Marla Residential Plot in Overseas Block",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "Park View City",
    address: "Overseas Block, Park View City, Islamabad",
    lat: 33.683,
    lng: 73.176,
    price: 13_500_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 10,
    areaUnit: "marla",
    areaSqft: 2250,
    parking: 0,
    furnishing: "Unfurnished",
    possession: "Possession",
    description:
      "A 10 Marla possession plot in the Overseas Block of Park View City, off Malot Road near Bani Gala. The plot is on a 40-foot road with all dues cleared, boundary marked and utilities available on the street, so construction can start as soon as the map is approved.",
    features: [
      "Possession and dues cleared",
      "40-foot road",
      "Boundary marked",
      "Utilities available on the street",
      "Ready for construction",
    ],
    amenities: ["Gated society", "24/7 security", "Carpeted roads", "Parks nearby", "Mosque nearby"],
    images: [photos.dev[0], photos.dev[1], photos.dev[2]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 590,
    daysAgo: 7,
  },
  {
    slug: "7-marla-house-bahria-town-phase-7-rawalpindi",
    title: "7 Marla Double Unit House near Spring North",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "rawalpindi",
    cityName: "Rawalpindi",
    locationArea: "Bahria Town Phase 7",
    address: "Bahria Town Phase 7, Rawalpindi",
    lat: 33.526,
    lng: 73.093,
    price: 41_000_000,
    priceUnit: "total",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 7,
    areaUnit: "marla",
    areaSqft: 1575,
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A 7 Marla double-unit house in Bahria Town Phase 7, walking distance from the Spring North commercial and the Phase 7 food street. Each floor has two bedrooms with attached baths, its own kitchen and lounge, so the house works for a joint family or for renting out one portion.",
    features: [
      "Double unit with separate kitchens",
      "Four bedrooms with attached baths",
      "Near Spring North commercial",
      "Tiled flooring throughout",
      "Car porch",
    ],
    amenities: ["Gated society", "24/7 security", "Commercial nearby", "Parks nearby", "Backup power"],
    images: [photos.villas[5], photos.interiors[3], photos.bedrooms[2], photos.interiors[4]],
    featured: false,
    verified: true,
    isNewProject: false,
    agentSlug: "ayesha-noor",
    views: 820,
    daysAgo: 8,
  },
];
