import { photos } from "@/lib/images";
import type { SeedProperty } from "./seed-data";

/**
 * DHA inventory across Lahore, Islamabad, Karachi, Multan, Gujranwala and
 * Peshawar: houses, plots, rentals and commercial units for client showings.
 * All copy is original editorial content. The `images` arrays only set the
 * gallery length — `seed-gallery.ts` hands every listing its own unique photos.
 */

const MARLA_SQFT = 225;
const KANAL_SQFT = 4500;

type DhaInput = Omit<SeedProperty, "priceUnit" | "verified" | "isNewProject" | "areaSqft"> & {
  areaSqft?: number;
};

function dha(input: DhaInput): SeedProperty {
  const areaSqft =
    input.areaSqft ??
    (input.areaUnit === "kanal"
      ? input.areaValue * KANAL_SQFT
      : input.areaUnit === "marla"
        ? input.areaValue * MARLA_SQFT
        : input.areaValue);
  return {
    ...input,
    areaSqft,
    priceUnit: input.purpose === "rent" ? "month" : "total",
    verified: true,
    isNewProject: false,
  };
}

const HOUSE_GALLERY = [photos.villas[0], photos.interiors[0], photos.bedrooms[0], photos.interiors[1], photos.bedrooms[1]];
const RENTAL_GALLERY = [photos.villas[2], photos.interiors[2], photos.bedrooms[2], photos.interiors[3]];
const PLOT_GALLERY = [photos.dev[0], photos.dev[1], photos.dev[2]];
const COMMERCIAL_GALLERY = [photos.commercial[0], photos.commercial[1], photos.commercial[2]];

export const dhaPropertySeed: SeedProperty[] = [
  // ─────────────────────────── DHA Lahore ───────────────────────────
  dha({
    slug: "2-kanal-designer-villa-dha-phase-5-lahore",
    title: "2 Kanal Designer Villa with Pool, DHA Phase 5",
    purpose: "buy",
    category: "house",
    propertyType: "Villa",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 5",
    address: "Block B, DHA Phase 5, Lahore",
    lat: 31.4629,
    lng: 74.4085,
    price: 195_000_000,
    negotiable: true,
    bedrooms: 6,
    bathrooms: 7,
    areaValue: 2,
    areaUnit: "kanal",
    parking: 5,
    furnishing: "Fully furnished",
    possession: "Available",
    description:
      "An architect-designed two-kanal villa on a 50-foot road in Block B, a short drive from Jalal Sons and the Phase 5 commercial. Double-height entrance lounge, six en-suite bedrooms, a temperature-controlled pool with deck, home cinema in the basement and a full-width lawn. Imported fittings throughout, solar backup and smart-home lighting.",
    features: [
      "Heated swimming pool with deck",
      "Home cinema and basement bar lounge",
      "Double-height entrance lounge",
      "Solar system with battery backup",
      "Smart-home lighting and CCTV",
      "Servant quarter with separate entry",
    ],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Commercial nearby", "Wide roads", "Mosque nearby"],
    images: HOUSE_GALLERY,
    featured: true,
    agentSlug: "hassan-rizvi",
    views: 2140,
    daysAgo: 1,
  }),
  dha({
    slug: "1-kanal-modern-house-dha-phase-7-lahore",
    title: "1 Kanal Brand-New Modern House, DHA Phase 7",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 7",
    address: "Block T, DHA Phase 7, Lahore",
    lat: 31.4402,
    lng: 74.4712,
    price: 82_500_000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    parking: 3,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "Just-completed one-kanal home in Block T with a clean modern elevation, wooden louvres and a landscaped front lawn. Five bedrooms with attached baths and walk-in wardrobes, a drawing-dining with a feature wall, a family lounge opening to the lawn and a separate kitchen for daily cooking. Near the Phase 7 park and Ring Road interchange.",
    features: [
      "Brand-new, never lived in",
      "Walk-in wardrobes in every bedroom",
      "Imported kitchen with separate dirty kitchen",
      "Covered garage for three cars",
      "Roof terrace with store",
    ],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Ring Road access", "Underground electricity"],
    images: HOUSE_GALLERY,
    featured: true,
    agentSlug: "hassan-rizvi",
    views: 1675,
    daysAgo: 2,
  }),
  dha({
    slug: "10-marla-house-dha-phase-8-air-avenue-lahore",
    title: "10 Marla House near Park, DHA Phase 8 Air Avenue",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 8",
    address: "Block Q, DHA Phase 8 (Air Avenue), Lahore",
    lat: 31.5068,
    lng: 74.4306,
    price: 57_000_000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 10,
    areaUnit: "marla",
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Park-facing ten-marla house in Air Avenue, minutes from Allama Iqbal International Airport and the Phase 8 commercial belt. Five bedrooms over two floors, TV lounges on both levels, a modern open kitchen and a rooftop room with terrace. Solid construction with porcelain tiles, hardwood doors and full-height glazing.",
    features: ["Park-facing location", "TV lounge on each floor", "Open kitchen with breakfast bar", "Rooftop room and terrace", "Porcelain tiles throughout"],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Near airport", "Commercial nearby"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 986,
    daysAgo: 3,
  }),
  dha({
    slug: "5-marla-house-dha-rahbar-sector-2-lahore",
    title: "5 Marla Double-Storey House, DHA Rahbar Sector 2",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Rahbar",
    address: "Block N, DHA Rahbar Sector 2 (Phase 11), Lahore",
    lat: 31.3895,
    lng: 74.2612,
    price: 21_500_000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 4,
    areaValue: 5,
    areaUnit: "marla",
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A compact, well-planned five-marla house in DHA Rahbar — the most affordable way into a DHA address. Three bedrooms with attached baths, a lounge with open kitchen, a drawing room at the front and a car porch. Close to Defence Road, the Rahbar mosque and the sector commercial.",
    features: ["Three attached bedrooms", "Open kitchen with lounge", "Front drawing room", "Car porch", "Near Defence Road"],
    amenities: ["Gated society", "24/7 security", "Mosque nearby", "Schools nearby"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 1210,
    daysAgo: 4,
  }),
  dha({
    slug: "1-kanal-residential-plot-dha-phase-7-lahore",
    title: "1 Kanal Possession Plot, DHA Phase 7 Block W",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 7",
    address: "Block W, DHA Phase 7, Lahore",
    lat: 31.4358,
    lng: 74.4801,
    price: 31_500_000,
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 1,
    areaUnit: "kanal",
    parking: 0,
    furnishing: "Not applicable",
    possession: "Possession",
    description:
      "Level one-kanal residential plot in Block W with possession, utilities on site and a 40-foot road. Construction is active on both sides, so the street is filling up quickly. A strong option for building a family home or holding for appreciation as Phase 7 matures.",
    features: ["Possession and utilities available", "40-foot road", "Level plot, ready to build", "All dues cleared"],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Underground electricity"],
    images: PLOT_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 742,
    daysAgo: 5,
  }),
  dha({
    slug: "10-marla-plot-dha-phase-9-prism-lahore",
    title: "10 Marla Plot, DHA Phase 9 Prism Block J",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 9 Prism",
    address: "Block J, DHA Phase 9 Prism, Lahore",
    lat: 31.4942,
    lng: 74.4688,
    price: 18_200_000,
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 10,
    areaUnit: "marla",
    parking: 0,
    furnishing: "Not applicable",
    possession: "Possession",
    description:
      "Ten-marla residential plot in Prism Block J with possession and a direct approach from Main Bedian Road. Near the Prism commercial zone and the planned central park. Clean transfer history and all development charges paid.",
    features: ["Possession plot", "Near Prism commercial zone", "Development charges paid", "Clean transfer history"],
    amenities: ["Gated society", "24/7 security", "Parks nearby"],
    images: PLOT_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 638,
    daysAgo: 6,
  }),
  dha({
    slug: "1-kanal-house-for-rent-dha-phase-6-lahore",
    title: "1 Kanal Furnished House for Rent, DHA Phase 6",
    purpose: "rent",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 6",
    address: "Block L, DHA Phase 6, Lahore",
    lat: 31.4771,
    lng: 74.4498,
    price: 425_000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    parking: 3,
    furnishing: "Fully furnished",
    possession: "Available",
    description:
      "A fully furnished one-kanal home for rent in Block L, ideal for expatriate families and corporate leases. Five bedrooms with attached baths, formal drawing-dining, a family lounge facing the lawn and a fitted kitchen with appliances. Walking distance to the Phase 6 main boulevard and close to the Lahore Grammar School campus.",
    features: ["Fully furnished with appliances", "Five attached bedrooms", "Private lawn", "Backup generator", "Corporate lease welcome"],
    amenities: ["Gated society", "24/7 security", "Schools nearby", "Commercial nearby"],
    images: RENTAL_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 904,
    daysAgo: 2,
  }),
  dha({
    slug: "10-marla-house-for-rent-dha-phase-4-lahore",
    title: "10 Marla House for Rent, DHA Phase 4 Block FF",
    purpose: "rent",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 4",
    address: "Block FF, DHA Phase 4, Lahore",
    lat: 31.4688,
    lng: 74.3994,
    price: 185_000,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 10,
    areaUnit: "marla",
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Well-kept ten-marla house for rent in Block FF, a settled family street near the Phase 4 main boulevard. Four bedrooms with attached baths, a lounge on each floor and a modern kitchen. Close to schools, the CCA commercial and Walton Road for a quick city commute.",
    features: ["Four attached bedrooms", "Lounge on each floor", "Freshly painted", "Gas and electricity connected"],
    amenities: ["Gated society", "24/7 security", "Schools nearby", "Commercial nearby", "Mosque nearby"],
    images: RENTAL_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 812,
    daysAgo: 3,
  }),
  dha({
    slug: "1-kanal-upper-portion-for-rent-dha-phase-3-lahore",
    title: "1 Kanal Upper Portion for Rent, DHA Phase 3",
    purpose: "rent",
    category: "house",
    propertyType: "Upper Portion",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 3",
    address: "Block Z, DHA Phase 3, Lahore",
    lat: 31.4731,
    lng: 74.3779,
    price: 135_000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1,
    areaUnit: "kanal",
    areaSqft: 2250,
    parking: 1,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "Separate-entrance upper portion of a one-kanal house in Block Z, a quiet street close to the Y Block market. Three bedrooms with attached baths, a TV lounge, kitchen and a private terrace. Separate electricity and gas meters; suits a small family or working couple.",
    features: ["Separate entrance", "Separate meters", "Private terrace", "Near Y Block market"],
    amenities: ["Gated society", "24/7 security", "Commercial nearby", "Parks nearby"],
    images: RENTAL_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 566,
    daysAgo: 5,
  }),
  dha({
    slug: "4-marla-commercial-shop-for-rent-dha-phase-6-lahore",
    title: "Ground-Floor Shop for Rent, DHA Phase 6 CCA",
    purpose: "rent",
    category: "shop",
    propertyType: "Shop",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 6",
    address: "CCA Main Boulevard, DHA Phase 6, Lahore",
    lat: 31.4749,
    lng: 74.4562,
    price: 450_000,
    negotiable: true,
    bedrooms: 0,
    bathrooms: 1,
    areaValue: 4,
    areaUnit: "marla",
    parking: 0,
    furnishing: "Bare shell",
    possession: "Available",
    description:
      "Glass-front ground-floor shop on the Phase 6 CCA main boulevard with heavy evening footfall from surrounding residential blocks. Double-height ceiling, washroom, front parking and signage rights. Suited to cafés, boutiques, pharmacies and bank branches.",
    features: ["Boulevard-facing glass front", "Double-height ceiling", "Signage rights", "Front customer parking"],
    amenities: ["24/7 security", "Commercial area", "Backup power"],
    images: COMMERCIAL_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 692,
    daysAgo: 4,
  }),
  dha({
    slug: "office-floor-for-sale-dha-phase-8-broadway-lahore",
    title: "Corporate Office Floor, DHA Phase 8 Broadway",
    purpose: "buy",
    category: "office",
    propertyType: "Office",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 8",
    address: "Broadway Commercial, DHA Phase 8, Lahore",
    lat: 31.5012,
    lng: 74.4378,
    price: 118_000_000,
    negotiable: true,
    bedrooms: 0,
    bathrooms: 4,
    areaValue: 5200,
    areaUnit: "sqft",
    parking: 6,
    furnishing: "Fitted",
    possession: "Available",
    description:
      "A full fitted office floor in a Broadway Commercial tower with a lift lobby, reception, twelve cabins, an open workstation hall for 60 seats, a boardroom and a pantry. Central air-conditioning and a building generator. Six reserved parking bays. Suits a software house or regional head office.",
    features: ["Full floor with reception", "Boardroom and twelve cabins", "Central air-conditioning", "Six reserved parking bays", "Building generator and lifts"],
    amenities: ["24/7 security", "Commercial area", "Backup power", "Elevator"],
    images: COMMERCIAL_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 518,
    daysAgo: 6,
  }),
  dha({
    slug: "8-marla-house-dha-phase-9-town-lahore",
    title: "8 Marla Corner House, DHA Phase 9 Town",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "lahore",
    cityName: "Lahore",
    locationArea: "DHA Phase 9 Town",
    address: "Block B, DHA Phase 9 Town, Lahore",
    lat: 31.4998,
    lng: 74.4552,
    price: 34_500_000,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 8,
    areaUnit: "marla",
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Corner eight-marla house in Phase 9 Town Block B with extra side-light and a wide car porch. Four bedrooms, two lounges, a modern kitchen and a rooftop store. The block is fully populated with a park, mosque and daily-needs market inside walking distance.",
    features: ["Corner plot with extra light", "Four bedrooms with attached baths", "Wide car porch", "Rooftop store and terrace"],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Mosque nearby", "Commercial nearby"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 874,
    daysAgo: 7,
  }),

  // ───────────────────────── DHA Islamabad ─────────────────────────
  dha({
    slug: "1-kanal-house-sector-a-dha-phase-2-islamabad",
    title: "1 Kanal House, Sector A, DHA Phase 2 Islamabad",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 2",
    address: "Sector A, DHA Phase 2, Islamabad",
    lat: 33.5296,
    lng: 73.1512,
    price: 72_000_000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    parking: 3,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A one-kanal family home in Sector A, one of the most established streets in DHA Phase 2, with quick access to GT Road and the Islamabad Expressway. Five bedrooms, a formal drawing-dining, a family lounge with fireplace and a green front lawn. Close to the Grand Jamia Mosque and the Phase 2 commercial.",
    features: ["Family lounge with fireplace", "Five attached bedrooms", "Front lawn", "Servant quarter", "Near Expressway"],
    amenities: ["Gated society", "24/7 security", "Mosque nearby", "Parks nearby", "Commercial nearby"],
    images: HOUSE_GALLERY,
    featured: true,
    agentSlug: "ayesha-noor",
    views: 1320,
    daysAgo: 2,
  }),
  dha({
    slug: "1-kanal-plot-sector-f-dha-phase-5-islamabad",
    title: "1 Kanal Plot, Sector F, DHA Phase 5 Islamabad",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 5",
    address: "Sector F, DHA Phase 5, Islamabad",
    lat: 33.4902,
    lng: 73.2011,
    price: 16_800_000,
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 1,
    areaUnit: "kanal",
    parking: 0,
    furnishing: "Not applicable",
    possession: "Possession",
    description:
      "One-kanal residential plot in Sector F with possession and a view of the Margalla foothills on clear days. Utilities are available and construction has started in the sector. A good entry point into DHA Islamabad at a fraction of Phase 2 prices.",
    features: ["Possession plot", "Hill-view location", "Utilities available", "Near Sector F park"],
    amenities: ["Gated society", "24/7 security", "Parks nearby"],
    images: PLOT_GALLERY,
    featured: false,
    agentSlug: "ayesha-noor",
    views: 604,
    daysAgo: 4,
  }),
  dha({
    slug: "10-marla-house-for-rent-dha-phase-1-islamabad",
    title: "10 Marla House for Rent, Sector F, DHA Phase 1",
    purpose: "rent",
    category: "house",
    propertyType: "House",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 1",
    address: "Sector F, DHA Phase 1, Islamabad",
    lat: 33.5478,
    lng: 73.1184,
    price: 150_000,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 10,
    areaUnit: "marla",
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Ten-marla house for rent in DHA Phase 1 Sector F, close to the DHA Phase 1 commercial and Lalazar. Four bedrooms with attached baths, two lounges, a modern kitchen and a small lawn. Easy access to the Islamabad Highway and Saddar.",
    features: ["Four attached bedrooms", "Two TV lounges", "Small front lawn", "Near Islamabad Highway"],
    amenities: ["Gated society", "24/7 security", "Schools nearby", "Commercial nearby"],
    images: RENTAL_GALLERY,
    featured: false,
    agentSlug: "ayesha-noor",
    views: 528,
    daysAgo: 3,
  }),
  dha({
    slug: "3-bed-apartment-dha-phase-2-islamabad",
    title: "3 Bed Luxury Apartment, DHA Phase 2 Islamabad",
    purpose: "buy",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "islamabad",
    cityName: "Islamabad",
    locationArea: "DHA Phase 2",
    address: "Sector J, DHA Phase 2, Islamabad",
    lat: 33.5222,
    lng: 73.1648,
    price: 38_500_000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1950,
    areaUnit: "sqft",
    parking: 1,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A three-bedroom apartment on the eighth floor of a completed tower in Sector J with open views towards the hills. Open living-dining, fitted kitchen, three bedrooms with attached baths, a balcony and reserved basement parking. The building has lifts, a gym, generator backup and round-the-clock security.",
    features: ["Hill-view balcony", "Fitted kitchen", "Reserved basement parking", "Gym and lifts in building"],
    amenities: ["Gated society", "24/7 security", "Elevator", "Gym", "Backup power"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "ayesha-noor",
    views: 716,
    daysAgo: 5,
  }),

  // ────────────────────────── DHA Karachi ──────────────────────────
  dha({
    slug: "500-sq-yd-bungalow-khayaban-e-shahbaz-dha-phase-6-karachi",
    title: "500 Sq. Yd. Bungalow, Khayaban-e-Shahbaz, DHA Phase 6",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA Phase 6",
    address: "Khayaban-e-Shahbaz, DHA Phase 6, Karachi",
    lat: 24.8061,
    lng: 67.0556,
    price: 215_000_000,
    negotiable: true,
    bedrooms: 6,
    bathrooms: 7,
    areaValue: 4500,
    areaUnit: "sqft",
    parking: 4,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A renovated 500 square-yard bungalow on Khayaban-e-Shahbaz, close to Bukhari Commercial and the Phase 6 sea-breeze belt. Six bedrooms with en-suite baths, a double-height lounge, a basement with a gym and home office, and a landscaped front garden. Includes a solar system and a water-storage upgrade.",
    features: ["Double-height formal lounge", "Basement gym and home office", "Solar system installed", "Large underground water tank", "Landscaped front garden"],
    amenities: ["24/7 security", "Near beach", "Commercial nearby", "Wide roads", "Mosque nearby"],
    images: HOUSE_GALLERY,
    featured: true,
    agentSlug: "bilal-shaikh",
    views: 1580,
    daysAgo: 1,
  }),
  dha({
    slug: "1000-sq-yd-villa-dha-phase-8-karachi",
    title: "1000 Sq. Yd. Sea-Side Villa, DHA Phase 8",
    purpose: "buy",
    category: "house",
    propertyType: "Villa",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA Phase 8",
    address: "Zone A, DHA Phase 8, Karachi",
    lat: 24.7832,
    lng: 67.0801,
    price: 425_000_000,
    negotiable: true,
    bedrooms: 7,
    bathrooms: 8,
    areaValue: 9000,
    areaUnit: "sqft",
    parking: 6,
    furnishing: "Fully furnished",
    possession: "Available",
    description:
      "A statement 1000 square-yard villa in Zone A, a short drive from Seaview and the Golf Club. Seven bedroom suites, formal and family lounges, a swimming pool framed by palms, a home theatre and a staff wing. Designed for entertaining, with a covered terrace overlooking the garden and parking for six cars.",
    features: ["Swimming pool with palm garden", "Seven bedroom suites", "Home theatre", "Covered entertaining terrace", "Separate staff wing"],
    amenities: ["24/7 security", "Near beach", "Golf club nearby", "Wide roads", "Commercial nearby"],
    images: HOUSE_GALLERY,
    featured: true,
    agentSlug: "bilal-shaikh",
    views: 2410,
    daysAgo: 1,
  }),
  dha({
    slug: "300-sq-yd-house-dha-phase-7-extension-karachi",
    title: "300 Sq. Yd. Brand-New House, DHA Phase 7 Extension",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA Phase 7 Extension",
    address: "Phase 7 Extension, DHA, Karachi",
    lat: 24.8196,
    lng: 67.0867,
    price: 76_000_000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 2700,
    areaUnit: "sqft",
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "Brand-new 300 square-yard house in Phase 7 Extension with a contemporary elevation and quality finishes. Five bedrooms with attached baths, drawing-dining, family lounge and a modern kitchen, plus a rooftop room. Close to Korangi Road and the Phase 7 commercial.",
    features: ["Brand-new construction", "Five attached bedrooms", "Modern kitchen", "Rooftop room", "Near Korangi Road"],
    amenities: ["24/7 security", "Commercial nearby", "Mosque nearby", "Schools nearby"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "bilal-shaikh",
    views: 846,
    daysAgo: 4,
  }),
  dha({
    slug: "3-bed-apartment-for-rent-bukhari-commercial-dha-phase-6-karachi",
    title: "3 Bed Apartment for Rent, Bukhari Commercial, DHA Phase 6",
    purpose: "rent",
    category: "apartment",
    propertyType: "Apartment",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA Phase 6",
    address: "Bukhari Commercial, DHA Phase 6, Karachi",
    lat: 24.8012,
    lng: 67.0612,
    price: 230_000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 2100,
    areaUnit: "sqft",
    parking: 1,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A bright three-bedroom apartment in Bukhari Commercial with a lift, a reserved parking bay and standby generator. Open lounge with balcony, three attached bedrooms and a fitted kitchen. Cafés, supermarkets and the Khayaban-e-Bukhari high street are on your doorstep.",
    features: ["Balcony off the lounge", "Fitted kitchen", "Reserved parking bay", "Lift and generator"],
    amenities: ["24/7 security", "Elevator", "Backup power", "Commercial nearby"],
    images: RENTAL_GALLERY,
    featured: false,
    agentSlug: "bilal-shaikh",
    views: 694,
    daysAgo: 2,
  }),
  dha({
    slug: "125-sq-yd-villa-dha-city-karachi",
    title: "125 Sq. Yd. Villa, DHA City Karachi Sector 16",
    purpose: "buy",
    category: "house",
    propertyType: "Villa",
    citySlug: "karachi",
    cityName: "Karachi",
    locationArea: "DHA City",
    address: "Sector 16, DHA City, Karachi",
    lat: 25.0312,
    lng: 67.4581,
    price: 18_500_000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaValue: 1125,
    areaUnit: "sqft",
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "A ready three-bedroom villa in DHA City Sector 16 on the Super Highway, with wide roads, parks and a planned community around it. Lounge with open kitchen, three bedrooms and a car porch. A sensible first home or rental investment in Karachi's fastest-growing DHA.",
    features: ["Ready to move in", "Open kitchen", "Car porch", "Wide boulevard access"],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Mosque nearby"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "bilal-shaikh",
    views: 902,
    daysAgo: 6,
  }),

  // ─────────────────── DHA Multan · Gujranwala · Peshawar ───────────────────
  dha({
    slug: "1-kanal-house-sector-s-dha-multan",
    title: "1 Kanal Modern House, Sector S, DHA Multan",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "multan",
    cityName: "Multan",
    locationArea: "DHA Multan",
    address: "Sector S, DHA Multan",
    lat: 30.1608,
    lng: 71.5214,
    price: 56_000_000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 6,
    areaValue: 1,
    areaUnit: "kanal",
    parking: 3,
    furnishing: "Semi-furnished",
    possession: "Available",
    description:
      "A modern one-kanal home in DHA Multan Sector S with a double-height lounge, five bedrooms and a lawn with a pergola seating area. Solar-ready roof, imported sanitary ware and a spacious kitchen. Close to the DHA Multan main boulevard, mosque and commercial hub.",
    features: ["Double-height lounge", "Lawn with pergola", "Solar-ready roof", "Imported sanitary ware"],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Mosque nearby", "Commercial nearby"],
    images: HOUSE_GALLERY,
    featured: true,
    agentSlug: "sana-ali",
    views: 1045,
    daysAgo: 2,
  }),
  dha({
    slug: "10-marla-house-dha-gujranwala",
    title: "10 Marla House, Block B, DHA Gujranwala",
    purpose: "buy",
    category: "house",
    propertyType: "House",
    citySlug: "gujranwala",
    cityName: "Gujranwala",
    locationArea: "DHA Gujranwala",
    address: "Block B, DHA Gujranwala",
    lat: 32.1452,
    lng: 74.2213,
    price: 31_000_000,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 5,
    areaValue: 10,
    areaUnit: "marla",
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Available",
    description:
      "One of the first completed ten-marla homes in DHA Gujranwala Block B, on a wide road near the main gate off GT Road. Four bedrooms, two lounges, a modern kitchen and a roof terrace. Secure, planned living with DHA management in Gujranwala.",
    features: ["Near main gate and GT Road", "Four attached bedrooms", "Two lounges", "Roof terrace"],
    amenities: ["Gated society", "24/7 security", "Parks nearby", "Wide roads"],
    images: HOUSE_GALLERY,
    featured: false,
    agentSlug: "hassan-rizvi",
    views: 588,
    daysAgo: 5,
  }),
  dha({
    slug: "10-marla-plot-sector-a-dha-peshawar",
    title: "10 Marla Plot, Sector A, DHA Peshawar",
    purpose: "buy",
    category: "plot",
    propertyType: "Plot",
    citySlug: "peshawar",
    cityName: "Peshawar",
    locationArea: "DHA Peshawar",
    address: "Sector A, DHA Peshawar",
    lat: 34.0418,
    lng: 71.5826,
    price: 9_800_000,
    negotiable: true,
    bedrooms: 0,
    bathrooms: 0,
    areaValue: 10,
    areaUnit: "marla",
    parking: 0,
    furnishing: "Not applicable",
    possession: "Possession",
    description:
      "Ten-marla residential plot with possession in DHA Peshawar Sector A, close to the Ring Road and Northern Bypass. Development is complete in the sector with carpeted roads and utilities. A secure address for building a family home in Peshawar.",
    features: ["Possession plot", "Carpeted roads", "Near Ring Road", "Utilities available"],
    amenities: ["Gated society", "24/7 security", "Parks nearby"],
    images: PLOT_GALLERY,
    featured: false,
    agentSlug: "ayesha-noor",
    views: 432,
    daysAgo: 7,
  }),
];
