"use client";
import Link from "next/link";
import { IconArrowRight, IconCheck, IconCompass, IconHeart, IconPhone, IconSearch, IconShield, IconSpark, IconStar, IconUpload, IconUser, IconBuilding } from "@/components/icons";
import { ResilientImage } from "@/components/resilient-image";
import { BlueTick } from "@/components/verified-badge";
import { Reveal } from "@/components/reveal";
import { PropertyCard } from "@/components/property-card";
import type { DealerProfile, PropertyWithDealer } from "@/lib/queries";
import { photo, photos } from "@/lib/images";
import { siteImages } from "@/lib/site-images";
const GREEN = "#1CA831";
const MOCKUP = "/WhatsApp%20Image%202026-10-05%20at%205.13.36%20PM-2.jpeg";

export function HomepageGrowthSections({ recentProperties, dealers }: { recentProperties: PropertyWithDealer[]; dealers: DealerProfile[] }) {
  const benefits = [
    [IconSearch, "Find Properties", "Search houses, apartments, plots and commercial spaces.", "/properties"],
    [IconBuilding, "Browse by Type", "Explore property categories made simple.", "/properties"],
    [IconShield, "Verified Dealers", "Check dealer profiles before you deal.", "/dealers"],
    [IconPhone, "Call & Connect", "Connect directly when you find the right property.", "/dealers"],
  ] as const;
  return <>
    <section className="bg-white py-9"><div className="ui-container grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {benefits.map(([Icon,title,text,href],i)=><Reveal key={title} delay={i*45}><Link href={href} className="group flex min-h-[145px] flex-col justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_14px_38px_-28px_rgba(6,28,51,.45)] transition hover:-translate-y-1 hover:border-[#1CA83155]"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#EFF8F0]" style={{color:GREEN}}><Icon className="h-5 w-5"/></span><span><span className="flex items-center justify-between font-sans font-bold text-navy-900">{title}<IconArrowRight className="h-4 w-4 text-slate-300 group-hover:translate-x-1"/></span><span className="mt-1.5 block text-xs leading-5 text-ink-muted">{text}</span></span></Link></Reveal>)}
    </div></section>

    <section className="bg-[#F7FAF8] py-14"><div className="ui-container"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow" style={{color:GREEN}}>Fresh on PropertiesPak</p><h2 className="mt-2 display-2">Recently Added Properties</h2><p className="mt-3 text-sm leading-7 text-ink-muted">See the latest homes, plots and commercial listings added to the marketplace.</p></div><Link href="/properties?sort=newest" className="btn btn-outline">View all recent listings <IconArrowRight className="h-4 w-4"/></Link></div>
      {recentProperties.length?<div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{recentProperties.slice(0,4).map((p,i)=><Reveal key={p.id} delay={i*50}><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_18px_38px_-28px_rgba(6,28,51,.45)]"><PropertyCard property={p} priority={i===0} propertyTypeBelowPrice/></div></Reveal>)}</div>:<div className="mt-9 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-sans font-semibold text-navy-900">New properties are being added.</p><Link href="/list-property" className="btn btn-green mt-5"><IconUpload className="h-4 w-4"/> List Your Property</Link></div>}
    </div></section>

    <section className="relative overflow-hidden bg-[linear-gradient(105deg,#061C33,#0B3550_58%,#103E3A)] py-16"><div className="ui-container relative"><p className="eyebrow text-white/70"><IconShield className="h-4 w-4" style={{color:GREEN}}/> Trusted connections</p><div className="mt-3 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="font-sans text-[2rem] font-bold leading-tight text-white sm:text-[2.8rem]">Verified Dealer Network</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/70">Dealers and agencies get a professional presence on PropertiesPak, while buyers can explore profiles before they deal.</p></div><Link href="/dealers" className="btn btn-ghost-light">Explore dealers <IconArrowRight className="h-4 w-4"/></Link></div>
      <div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{dealers.slice(0,4).map((d,i)=><Reveal key={d.id} delay={i*50}><Link href={d.slug?"/dealers/"+d.slug:"/dealers"} className="group rounded-2xl border border-white/10 bg-white/[.055] p-4 transition hover:-translate-y-1"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center overflow-hidden rounded-xl bg-white/10">{d.companyLogo||d.avatarUrl?<ResilientImage src={d.companyLogo||d.avatarUrl||""} alt="" width={96} height={96} className="h-full w-full object-cover"/>:<IconUser className="h-5 w-5 text-white/60"/>}</span><span className="min-w-0"><span className="flex items-center gap-1.5 truncate font-sans text-sm font-bold text-white">{d.agency||d.name}{d.isVerified?<BlueTick className="h-4 w-4"/>:null}</span><span className="mt-1 block text-xs text-white/50">{d.cityName||"Pakistan"}</span></span></div><div className="mt-4 flex justify-between text-xs text-white/50"><span>{d.listings ? String(d.listings)+" listings" : "View profile"}</span><IconArrowRight className="h-4 w-4" style={{color:GREEN}}/></div></Link></Reveal>)}</div>
    </div></section>

    <section className="bg-white py-16"><div className="ui-container grid items-center gap-10 lg:grid-cols-[.86fr_1.14fr]"><Reveal><div className="relative overflow-hidden rounded-[24px] shadow-[0_30px_70px_-32px_rgba(6,28,51,.42)]"><ResilientImage src={siteImages.aboutVilla.webp[0].src} fallbackSrc={photo(photos.villas[0],1200,900)} alt="Contemporary luxury home" width={1100} height={860} className="h-[360px] w-full object-cover sm:h-[460px]"/><div className="absolute inset-x-4 bottom-4 rounded-2xl bg-navy-950/80 p-4 text-white backdrop-blur"><span className="flex items-center gap-2 text-xs font-semibold"><span className="grid h-8 w-8 place-items-center rounded-lg" style={{background:GREEN}}><IconStar className="h-4 w-4"/></span>Built for serious property businesses</span></div></div></Reveal><Reveal delay={80}><div><p className="eyebrow" style={{color:GREEN}}>For agents & owners</p><h2 className="mt-3 display-2">Get More Visibility, More Inquiries and Grow Your Real Estate Business</h2><p className="mt-4 text-sm leading-7 text-ink-muted">Put your properties where people are already searching. Showcase inventory professionally and turn interest into direct conversations.</p><div className="mt-7 space-y-3">{["Reach buyers and tenants searching across Pakistan","Give every property a polished, shareable listing page","Make your profile and listings easier to discover","Turn views into direct calls and genuine inquiries"].map(x=><div key={x} className="flex gap-3 text-sm text-navy-900"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#EEF7EF]" style={{color:GREEN}}><IconCheck className="h-3.5 w-3.5"/></span>{x}</div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/list-property" className="btn btn-green">List Your Property <IconArrowRight className="h-4 w-4"/></Link><Link href="/dealers" className="btn btn-outline">Explore Dealer Network</Link></div><p className="mt-3 text-xs text-ink-muted">Free listing • No hidden charges</p></div></Reveal></div></section>

    <section className="bg-[#F5F8F6] py-16"><div className="ui-container grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><Reveal><div><p className="eyebrow" style={{color:GREEN}}>PropertiesPak mobile</p><h2 className="mt-3 display-2">Download PropertiesPak App</h2><p className="mt-4 text-sm leading-7 text-ink-muted">Search, save and stay close to your next property on the go.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[[IconSearch,"Search faster","Find properties by city, type and budget."],[IconHeart,"Save favourites","Keep properties you want to revisit."],[IconSpark,"Get updates","Stay close to new listings."]].map(([I,t,x])=><div key={String(t)} className="rounded-2xl border border-slate-200 bg-white p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EEF7EF]" style={{color:GREEN}}><I className="h-4 w-4"/></span><p className="mt-3 font-sans text-sm font-bold text-navy-900">{String(t)}</p><p className="mt-1 text-xs leading-5 text-ink-muted">{String(x)}</p></div>)}</div><Link href="/properties" className="btn btn-green mt-7">Start searching <IconSearch className="h-4 w-4"/></Link></div></Reveal><Reveal delay={90}><div className="relative mx-auto w-full max-w-[480px]"><div className="absolute -inset-8 rounded-[40px] bg-[#1CA83118] blur-3xl"/><div className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-3 shadow-[0_30px_75px_-34px_rgba(6,28,51,.46)]"><ResilientImage src={MOCKUP} fallbackSrc={siteImages.smarterLiving.webp[0].src} alt="PropertiesPak app visual" width={900} height={1100} className="h-[480px] w-full rounded-[20px] object-cover object-top sm:h-[580px]"/></div></div></Reveal></div></section>

    <section className="relative overflow-hidden py-20"><ResilientImage src={photo(photos.dev[2],1800,1000)} alt="" width={1800} height={1000} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,16,28,.94),rgba(4,16,28,.72)_50%,rgba(4,16,28,.42))]"/><div className="ui-container relative"><p className="eyebrow text-white/70"><IconCompass className="h-4 w-4" style={{color:GREEN}}/> Start your search</p><h2 className="mt-3 max-w-3xl font-sans text-[2rem] font-bold leading-tight text-white sm:text-[3.35rem]">Your Next Property is Just a Click Away</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">Buy, rent or list your property on Pakistan's growing real estate marketplace. Explore the right location, compare options and connect with people ready to move.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/properties" className="btn btn-green">Find a Property <IconArrowRight className="h-4 w-4"/></Link><Link href="/list-property" className="btn btn-ghost-light">List Your Property <IconUpload className="h-4 w-4"/></Link></div></div></section>
  </>;
}